apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
  namespace: newgupe
  labels:
    app: kafka-broker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - name: kafka-broker
          image: wurstmeister/kafka
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc  # Change this to your desired PVC name

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: newgupe
  labels:
    app: kafka-broker
spec:
  type: LoadBalancer
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
  selector:
    app: kafka-broker

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc  # Change this to your desired PVC name
  namespace: newgupe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi  # Change this to your desired storage size
